config/routes.rb
Rails.application.routes.draw do
  resources :sections
  resources :semesters
  resources :courses
  resources :prefixes
  resources :students
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "landing_page#index"
end

app/models/semester.rb
class Semester < ApplicationRecord
  has_many :sections, dependent: :nullify

  enum semester: { spring: 'Spring', summer: 'Summer', fall: 'Fall', winter: 'Winter' }
end

app/controllers/semesters_controller.rb
class SemestersController < ApplicationController
  before_action :set_semester, only: %i[ show edit update destroy ]

  # GET /semesters or /semesters.json
  def index
    @semesters = Semester.all
  end

  # GET /semesters/1 or /semesters/1.json
  def show
  end

  # GET /semesters/new
  def new
    @semester = Semester.new
  end

  # GET /semesters/1/edit
  def edit
  end

  # POST /semesters or /semesters.json
  def create
    @semester = Semester.new(semester_params)

    respond_to do |format|
      if @semester.save
        format.html { redirect_to semester_url(@semester), notice: "Semester was successfully created." }
        format.json { render :show, status: :created, location: @semester }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @semester.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /semesters/1 or /semesters/1.json
  def update
    respond_to do |format|
      if @semester.update(semester_params)
        format.html { redirect_to semester_url(@semester), notice: "Semester was successfully updated." }
        format.json { render :show, status: :ok, location: @semester }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @semester.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /semesters/1 or /semesters/1.json
  def destroy
    @semester.destroy

    respond_to do |format|
      format.html { redirect_to semesters_url, notice: "Semester was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_semester
      @semester = Semester.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def semester_params
      params.require(:semester).permit(:semester, :year)
    end
end

app/views/semesters/_form.html.erb
<%= form_with(model: semester) do |form| %>
  <% if semester.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(semester.errors.count, "error") %> prohibited this semester from being saved:</h2>

      <ul>
        <% semester.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :semester, style: "display: block" %>
    <%= form.select :semester, options_for_select(Semester.semesters.keys), style: "display: block" %>
  </div>

  <div>
    <%= form.label :year, style: "display: block" %>
    <%= form.number_field :year %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/semesters/_semester.html.erb
<hr>
<div id="<%= dom_id semester %>">
  <p>
    <strong>Semester:</strong>
    <%= semester.semester.present? ? semester.semester : 'Semester not set' %>
  </p>

  <p>
    <strong>Year:</strong>
    <%= semester.year || 'Year not set' %>
  </p>

</div>

app/views/semesters/edit.html.erb
<h1>Editing semester</h1>

<%= render "form", semester: @semester %>

<br>

<div>
  <%= link_to "Show this semester", @semester %> |
  <%= link_to "Back to semesters", semesters_path %>
</div>

app/views/semesters/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Semesters</h1>

<div id="semesters">
  <% @semesters.each do |semester| %>
    <%= render semester %>
    <p>
      <%= link_to "Show this semester", semester %>
    </p>
  <% end %>
</div>

<%= link_to "New semester", new_semester_path %>

app/views/semesters/new.html.erb
<h1>New semester</h1>

<%= render "form", semester: @semester %>

<br>

<div>
  <%= link_to "Back to semesters", semesters_path %>
</div>

app/views/semesters/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @semester %>

<h3>Sections: </h3>
<% @semester.sections.each do |section| %>
  <%= render section %>
<% end %>

<div>
  <%= link_to "Edit this semester", edit_semester_path(@semester) %> |
  <%= link_to "Back to semesters", semesters_path %>

  <%= button_to "Destroy this semester", @semester, method: :delete %>
</div>