config/routes.rb
Rails.application.routes.draw do
  resources :sections
  resources :semesters
  resources :courses
  resources :prefixes
  resources :students
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "landing_page#index"
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :sections_students, dependent: :destroy
  has_many :sections, through: :sections_students

  validates :first_name, :last_name, :email, :student_id, :physical_address, :phone_number, presence: true
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
    @q = Student.ransack(params[:q])
    @students = @q.result(distinct: true)
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:first_name, :last_name, :email, :physical_address, :phone_number, :student_id, section_ids: [])
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :physical_address, style: "display: block" %>
    <%= form.text_area :physical_address %>
  </div>

  <div>
    <%= form.label :phone_number, style: "display: block" %>
    <%= form.number_field :phone_number %>
  </div>

  <div>
    <%= form.label :student_id, style: "display: block" %>
    <%= form.number_field :student_id %>
  </div>

  <div>
    <%= form.label :section, style: "display: block" %>
    <%= form.collection_select :section_ids, Section.all, :id, :CRN, {}, { multiple: true} %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/students/_student.html.erb
<hr>

<div id="<%= dom_id student %>">
  <p>
    <strong>First name:</strong>
    <%= student.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= student.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= student.email %>
  </p>

  <p>
    <strong>Physical address:</strong>
    <%= student.physical_address %>
  </p>

  <p>
    <strong>Phone number:</strong>
    <%= student.phone_number %>
  </p>

  <p>
    <strong>Student:</strong>
    <%= student.student_id %>
  </p>

  <p>
    <strong>Section CRNs:</strong>
    <% if student.sections.any? %>
    <ul>
      <% student.sections.each do |section| %>
        <li>
          <%= link_to section.CRN, section %>
        </li>
      <% end %>
    </ul>
  <% else %>
    Empty
  <% end %>
  </p>
</div>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Show this student", @student %> |
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Students</h1>
<h3>Search students by:</h3>
<%= search_form_for @q do |f| %>
  <div style="display: flex; flex-wrap: wrap">
    <div style="width: 50%">
      <%= f.label :first_name_cont %>
      <%= f.search_field :first_name_cont %>
    </div>

    <div style="width: 50%">
      <%= f.label :last_name_cont %>
      <%= f.search_field :last_name_cont %>
    </div>

    <div style="width: 50%">
      <%= f.label :email_cont %>
      <%= f.search_field :email_cont %>
    </div>

    <div style="width: 50%">
      <%= f.label :student_id_eq %>
      <%= f.search_field :student_id_eq %>
    </div>
  </div>

  <%= f.submit "Search" %> <br>
  <%= link_to "Clear Search", request.path, class: "cancel-button" %>
  <hr>
<% end %>
<%= button_to "New student", new_student_path, method: :get %>
<div id="students">
  <% @students.each do |student| %>
    <%= render student %>
    <p>
      <%= link_to "Show this student", student %>
    </p>
  <% end %>
</div>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @student %>

<div>
  <%= link_to "Edit this student", edit_student_path(@student) %> |
  <%= link_to "Back to students", students_path %>

  <%= button_to "Destroy this student", @student, method: :delete %>
</div>