config/routes.rb
Rails.application.routes.draw do
  resources :sections
  resources :semesters
  resources :courses
  resources :prefixes
  resources :students
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "landing_page#index"
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :course
  belongs_to :semester
  has_many :sections_students, dependent: :destroy
  has_many :students, through: :sections_students
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: %i[ show edit update destroy ]

  # GET /sections or /sections.json
  def index
    @sections = Section.all
  end

  # GET /sections/1 or /sections/1.json
  def show
  end

  # GET /sections/new
  def new
    @section = Section.new
  end

  # GET /sections/1/edit
  def edit
  end

  # POST /sections or /sections.json
  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to section_url(@section), notice: "Section was successfully created." }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1 or /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to section_url(@section), notice: "Section was successfully updated." }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1 or /sections/1.json
  def destroy
    @section.destroy

    respond_to do |format|
      format.html { redirect_to sections_url, notice: "Section was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def section_params
      params.require(:section).permit(:CRN, :course_id, :semester_id, student_ids: [])
    end
end

app/views/sections/_form.html.erb
<%= form_with(model: section) do |form| %>
  <% if section.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
        <% section.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :CRN, style: "display: block" %>
    <%= form.text_field :CRN %>
  </div>

  <div>
    <%= form.label :course_id, style: "display: block" %>
    <%= form.select :course_id, Course.all.map { |c| ["#{c.prefix.prefix} #{c.number} #{c.name}", c.id] } %>
  </div>

  <div>
    <%= form.label :semester_id, style: "display: block" %>
    <%= form.select :semester_id, Semester.all.map { |s| ["#{s.semester} #{s.year}", s.id] } %>
  </div>

  <div>
    <%= form.label :section, style: "display: block" %>
    <%= form.collection_select :student_ids, Student.all, :id, :email, {}, { multiple: true} %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/sections/_section.html.erb
<hr>
<div id="<%= dom_id section %>">
  <p>
    <strong>Crn:</strong>
    <%= section.CRN %>
  </p>

  <p>
    <strong>Course:</strong>
    <% if section.course %>
      <%= link_to "#{section.course.prefix.prefix} #{section.course.number} #{section.course.name}", section.course %>
    <% else %>
      Course not set
    <% end %>
  </p>

  <p>
    <strong>Semester:</strong>
    <% if section.semester %>
      <%= link_to "#{section.semester.semester} #{section.semester.year}", section.semester %>
    <% else %>
      Semester not set
    <% end %>
  </p>

  <p>
    <strong>Students:</strong>
    <% if section.students.any? %>
    <ul>
      <% section.students.each do |student| %>
        <li>
          <%= link_to student&.email, student %>
        </li>
      <% end %>
    </ul>
  <% else %>
    No students
  <% end %>

  </p>

</div>

app/views/sections/edit.html.erb
<h1>Editing section</h1>

<%= render "form", section: @section %>

<br>

<div>
  <%= link_to "Show this section", @section %> |
  <%= link_to "Back to sections", sections_path %>
</div>

app/views/sections/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Sections</h1>

<div id="sections">
  <% @sections.each do |section| %>
    <%= render section %>
    <p>
      <%= link_to "Show this section", section %>
    </p>
  <% end %>
</div>

<%= link_to "New section", new_section_path %>

app/views/sections/new.html.erb
<h1>New section</h1>

<%= render "form", section: @section %>

<br>

<div>
  <%= link_to "Back to sections", sections_path %>
</div>

app/views/sections/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @section %>

<div>
  <%= link_to "Edit this section", edit_section_path(@section) %> |
  <%= link_to "Back to sections", sections_path %>

  <%= button_to "Destroy this section", @section, method: :delete %>
</div>