config/routes.rb
Rails.application.routes.draw do
  resources :sections
  resources :semesters
  resources :courses
  resources :prefixes
  resources :students
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "landing_page#index"
end

app/models/prefix.rb
class Prefix < ApplicationRecord
  has_many :courses, dependent: :nullify
end

app/controllers/prefixes_controller.rb
class PrefixesController < ApplicationController
  before_action :set_prefix, only: %i[ show edit update destroy ]

  # GET /prefixes or /prefixes.json
  def index
    @prefixes = Prefix.all
  end

  # GET /prefixes/1 or /prefixes/1.json
  def show
  end

  # GET /prefixes/new
  def new
    @prefix = Prefix.new
  end

  # GET /prefixes/1/edit
  def edit
  end

  # POST /prefixes or /prefixes.json
  def create
    @prefix = Prefix.new(prefix_params)

    respond_to do |format|
      if @prefix.save
        format.html { redirect_to prefix_url(@prefix), notice: "Prefix was successfully created." }
        format.json { render :show, status: :created, location: @prefix }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @prefix.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prefixes/1 or /prefixes/1.json
  def update
    respond_to do |format|
      if @prefix.update(prefix_params)
        format.html { redirect_to prefix_url(@prefix), notice: "Prefix was successfully updated." }
        format.json { render :show, status: :ok, location: @prefix }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @prefix.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prefixes/1 or /prefixes/1.json
  def destroy
    @prefix.destroy

    respond_to do |format|
      format.html { redirect_to prefixes_url, notice: "Prefix was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prefix
      @prefix = Prefix.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def prefix_params
      params.require(:prefix).permit(:prefix)
    end
end

app/helpers/prefixes_helper.rb
module PrefixesHelper
end

app/views/prefixes/_form.html.erb
<%= form_with(model: prefix) do |form| %>
  <% if prefix.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(prefix.errors.count, "error") %> prohibited this prefix from being saved:</h2>

      <ul>
        <% prefix.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :prefix, style: "display: block" %>
    <%= form.text_field :prefix %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/prefixes/_prefix.html.erb
<hr>
<div id="<%= dom_id prefix %>">
  <p>
    <strong>Prefix:</strong>
    <%= prefix.prefix.present? ? prefix.prefix : 'Prefix not set' %>
  </p>

</div>

app/views/prefixes/edit.html.erb
<h1>Editing prefix</h1>

<%= render "form", prefix: @prefix %>

<br>

<div>
  <%= link_to "Show this prefix", @prefix %> |
  <%= link_to "Back to prefixes", prefixes_path %>
</div>

app/views/prefixes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Prefixes</h1>

<div id="prefixes">
  <% @prefixes.each do |prefix| %>
    <%= render prefix %>
    <p>
      <%= link_to "Show this prefix", prefix %>
    </p>
  <% end %>
</div>

<%= link_to "New prefix", new_prefix_path %>

app/views/prefixes/new.html.erb
<h1>New prefix</h1>

<%= render "form", prefix: @prefix %>

<br>

<div>
  <%= link_to "Back to prefixes", prefixes_path %>
</div>

app/views/prefixes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @prefix %>

<div>
  <%= link_to "Edit this prefix", edit_prefix_path(@prefix) %> |
  <%= link_to "Back to prefixes", prefixes_path %>

  <%= button_to "Destroy this prefix", @prefix, method: :delete %>
</div>